version: '3'
volumes:
    mysql_data:
services:
    docker-rabbitmq-nginx-service:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        container_name: docker-rabbitmq-nginx-container
        volumes:
            - ./../:/var/www/docker-rabbitmq/
        ports: ['8901:80']
        networks:
            - docker-rabbitmq-network
    docker-rabbitmq-php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: docker-rabbitmq-php-container
        ports: ['9101:9000']
        volumes:
            - ./../:/var/www/docker-rabbitmq/
            - ./../vendor:/var/www/docker-rabbitmq/vendor
        networks:
            - docker-rabbitmq-network
    docker-rabbitmq-mysql-service:
        image: mysql
        container_name: docker-rabbitmq-mysql-container
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--authentication_policy=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports: ['3906:3306']
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - docker-rabbitmq-network
    docker-rabbitmq-phpmyadmin-service:
        image: phpmyadmin/phpmyadmin:latest
        container_name: docker-rabbitmq-phpmyadmin-container
        environment:
            PMA_HOST: docker-rabbitmq-mysql-service
            PMA_USER: root
            PMA_PASSWORD: root
        ports: ['8902:80']
        depends_on:
            - docker-rabbitmq-mysql-service
        volumes:
            - ./phpmyadmin/:/var/www/docker-rabbitmq/docker/phpmyadmin/
        networks:
            - docker-rabbitmq-network
    docker-rabbitmq-rabbit-service:
        image: rabbitmq:3-management-alpine
        container_name: docker-rabbitmq-rabbit-container
        ports: ['5672:5672', '15672:15672']
        volumes:
            - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - docker-rabbitmq-network

networks:
    docker-rabbitmq-network:
        driver: bridge
